- name: Install Zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
    update_cache: yes
    validate_certs: yes
  become: yes
  when: ansible_os_family == 'RedHat'
