- name: Elasticsearch repository
  yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    state: present
  become: yes

- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: yes

- name: Install latest Elasticsearch
  yum:
    name: elasticsearch-oss
  become: yes

- name: Copy elasticsearch configuration file
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  become: yes

- name: daemon_reload
  shell: systemctl daemon-reload
  become: yes

- name: restart/enable elasticsearch service
  service:
    name: elasticsearch.service
    state: restarted
    enabled: yes
  become: yes
