- name:
  lineinfile:
    path: /etc/rsyslog.conf
    line: '*.* @192.168.1.21:1514;RSYSLOG_SyslogProtocol23Format'
  become: yes

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted
  become: yes
