- name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes

- name: SELinux - Graylog REST API and web interface
  seport:
    ports: 9000
    proto: tcp
    setype: http_port_t
    state: present
  become: yes

- name: SELinux - Elasticsearch
  seport:
    ports: 9200
    proto: tcp
    setype: http_port_t
    state: present
  become: yes

- name: SELinux - Graylog REST API and web interface
  seport:
    ports: 27017
    proto: tcp
    setype: mongod_port_t
    state: present
  become: yes
