- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: /etc/ssl/certs/{{cert_domain}}.csr
    privatekey_path: /etc/ssl/private/{{cert_domain}}.pem
    privatekey_passphrase: "{{cert_passphrasse}}"
    common_name: "{{common_name}}"
    country_name: BR
    email_address: admin@{{cert_domain}}
    locality_name: Sao_Paulo
    state_or_province_name: Sao_Paulo
    owner: root
    group: root
    mode: '644'
    organization_name: Reply_do_Brasil
    organizational_unit_name: Reply_do_Brasil
  become: yes
