- name: install PyOpenSSL
  yum:
    name: pyOpenSSL.x86_64
    state: latest
  become: yes

- name: Creates directory
  file:
    path: /etc/ssl/private/
    state: directory
    owner: root
    group: root
    mode: '744'
  become: yes
