---
- name: Install Zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
    update_cache: yes
    validate_certs: yes
  become: yes

- name: Install Zabbix server, Agent, Zabbix fronted, and mysql client
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-agent
      - centos-release-scl
      - mysql
  become: yes

- name: Copy zabbix repo file, enabling zabbix-frontend repository
  copy:
    src: files/zabbix.repo
    dest: /etc/yum.repos.d/zabbix.repo
  become: yes

- name: Install Zabbix frontend packages
  yum:
    name: 
      - zabbix-web-mysql-scl
      - zabbix-apache-conf-scl
  become: yes

#- name: Import initial schema and data to database
#  community.mysql.mysql_db:
#    state: import
#    login_user: "{{mysql_zabbix_user}}"
#    login_password: "{{mysql_zabbix_user_password}}"
#    name: "{{mysql_zabbix_database_name}}"
#    encoding: utf8
#    collation: utf8_bin
#    target: /usr/share/doc/zabbix-server-mysql-5.0.5/create.sql.gz
#  become: yes

- name: Import initial schema and data to database
  shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u"{{mysql_zabbix_user}}" -p"{{mysql_zabbix_user_password}}" -h"{{mysql_server_ipaddreses}}" -D"{{mysql_zabbix_database_name}}" || echo "not imported. It's been probably already imported"
  args:
    warn: no
  register: import_result
  become: yes

- meta: flush_handlers
- debug:
      var: import_result

- name: 'Configure zabbix server configuration file'
  template:
    src: 'templates/zabbix_server.conf'
    dest: '/etc/zabbix/zabbix_server.conf'
  become: yes

- name: 'Configure php zabbix configuration file'
  template:
    src: 'templates/zabbix.conf'
    dest: '/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf'
  become: yes

- name: zabbix-server service
  service: 
    name: zabbix-server
    state: restarted
    enabled: yes
  become: yes

- name: zabbix-agent service
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  become: yes

- name: httpd service
  service:  
    name: httpd
    state: restarted
    enabled: yes
  become: yes

- name: rh-php72-php-fpm service
  service:
    name: rh-php72-php-fpm
    state: restarted
    enabled: yes
  become: yes

- name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes