---
- name: Start mysqld service, if not already started
  systemd:
    name: mysqld
    state: restarted
  become: yes
  tags:
    - database

- name: Create MySQL database for Zabbix
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_zabbix_database_name }}"
    encoding: utf8
    collation: utf8_bin
    state: present
  tags:
    - database

- name: 'Create user for Zabbix database in MySQL'
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_zabbix_user }}"
    password: "{{ mysql_zabbix_user_password }}"
    priv: "{{ mysql_zabbix_database_name }}.*:ALL"
    state: present
    host: '{{ item }}'
  with_items:
    - "{{ zabbix_server_ipaddress }}"
  tags:
    - database